### PR TITLE
patch in-page alignment

### LINKED ISSUE #12: RTL titles should align right.
Titles should align right.

It looks like this:
Screen Shot 2020-08-28 at 23 05 27

And should look like this:
Screen Shot 2020-08-28 at 23 06 59

### PR DESCRIPTION
**Pull request by dragonwocky**

### CODE REVIEW

**Comment by obahareth** [comment]
Hey @dragonwocky, I am sorry this has taken ages, this is a very valuable contribution and I'll make sure to get it merged and deployed on Friday.

**Comment by obahareth** [comment]
@dragonwocky Could you re-make the PR? because it says to me this PR is from an unknown/deleted/private repository.

Screen Shot 2020-12-05 at 10 33 17 PM

**Comment by dragonwocky** [comment]
@obahareth yeah, i deleted the repository while cleaning some things up.

you should still be able to merge it and you can view changes under the commits tab, is a new PR necessary?

**Comment by obahareth** [comment]
@dragonwocky I wanted to check it out and try it out locally and I also tried hitting the "View file" button on the changes tab but it gave me a 404, I'd have to copy your changes one by one. I can do that if there's any bother in making a new PR but I thought I'd try and ask first.

**Comment by dragonwocky** [comment]
Ah. I can make later today, but I don't have a copy of the full file either so it'd still be a copy/paste process, sorry. Might be easier to just do it if you're free now.


If you use the notion-enhancer you can test it there: it's functionally equivalent, just refactored a bit from here to cut down on some unnecessary things.

**Comment by dragonwocky** [comment]
actually @obahareth i found a whole file/branch that's still linked to this: https://github.com/obahareth/notion-rtl/blob/57e0985f76b4d93c7fb48a7aad08ab9469c5c0d8/src/index.js

**Comment by obahareth** [comment]
@dragonwocky Check #19, I added your changes there and supported more block types as well, and I also updated the [public pages](https://www.notion.so/obahareth/Notion-RTL-Tests-8bee4db6585343fc8bae93b791edd726) with more content/block types for testing out the extension. I'll be releasing it soon.

Also do you think using something like using git submodules in the desktop repo to make it easier pull the changes in from this repo might help you out?

**Comment by dragonwocky** [comment]
thanks @obahareth, i'll see if I can port those across.
submodules wouldn't really be the best solution, because most of the contents of this repo aren't useful to the enhancer. also, a bunch of what is in `index.js` is either already handled by the enhancer (or at least is in the work-in-progress version, e.g. handling a mutations queue and waiting until the page is loaded), so when I do copy this across the code looks pretty different.

**Pull request closed without merging**
