### PR TITLE
Migrate to mutation observer

### PR DESCRIPTION
**Pull request by Fahme**
Fixes https://github.com/obahareth/notion-rtl/issues/2

### CODE REVIEW

**Comment by Fahme** [comment]
@obahareth ready for review

**Comment by dragonwocky** [comment]
just a btw: I'm using a modified version of this implementation for https://github.com/obahareth/notion-rtl/issues/3#issuecomment-673374039

**Comment by dragonwocky** [comment]
As far as I can tell this is only "more performant" because it only observes page content: doesn't this mean that if e.g. you typed text in the searchbar or sidebar it wouldn't be aligned correctly? (Sure it's all applied on page load once, but Notion often deletes/re-adds elements.)

There are some performance things I could do (e.g. debounce, recursively looping through the mutationsList and checking for the presence of innerText) - but I don't think only observing page content is worth the small boost.

**Comment by obahareth** [comment]
Thanks @Fahme for your contribution, I'll be taking a look at it now. Sorry I took so long to get back to you.

@dragonwocky Your comment is definitely valid but I think the performance boost from this is a good addition because right now this extension is only altering page content at the moment. We can consider alternative approaches in the future if we start applying RTL everywhere.

I think we'd also need #5 before that because I think a lot of people still prefer using Notion's UI in LTR and only want page content to be RTL, so having a config option to select if you want the UI to be RTL is also a good idea.

**Comment by obahareth** [comment]
Hey @Fahme, so I noticed one issue with this approach. When I load up Notion in a non-RTL page and then click a link to an RTL page it does not work until I reload.

Here's a video showcasing this
https://www.loom.com/share/ccd1183150f04eedbce41643bc76b919

The first time the page is shown, I navigated to it from by clicking a link to it from an LTR page, you'll notice the content was all LTR. The second time where you see all the content working properly is when I reloaded the page with CMD+R.

By the way these [public Notion pages](https://www.notion.so/obahareth/Notion-RTL-Tests-8bee4db6585343fc8bae93b791edd726) might help you with testing the extension out (I just added them to the README).

**Comment by Fahme** [comment]
@obahareth i can replicate, it's due to the nature of the routing in notion website, the bad part is that we can't detect route changes with events like popstate, pushstate or replacestate, so what we can do is use the browser API ```webNavigation.onHistoryStateUpdated``` in a background script of the extension and send over message to the content script if the route change to do the necessary styling afterwards. 

Now the down side for that IMO is that we will need to ask the user for an extra permission in the browser which is the web history perm.. so probably will need to add a disclaimer in the store and the readme as well. However this for sure is better that keeping the interval in the page.

what do you think, and do you have an alternative ?

**Comment by Fahme** [comment]
after thinking about as well since this is an open source tool it's not big of deal to ask for permission as anyone can see how this ext is using their browser history in notion but a disclaimer is a good choice.

**Comment by Fahme** [comment]
@obahareth updated the PR without the hack i mentioned in my previous comments, i'm purely depending on a performant mutation observer method to do everything, i also did multiple regression tests as well in different scenarios and things seems to look ok for me, let me know your opinion.

i've added some comments in code to explain how the logic is working feel free to make it more descriptive if you like !


p.s. i've changed the folder structure of the project and added some prettier rules for vs-code as well for general code organization etc ...

**Comment by dragonwocky** [comment]
By the way, https://github.com/Fahme/notion-rtl/blob/fix/issue-2/src/index.js#L19 needs to be `document.querySelectorAll("div[placeholder='List'], div[placeholder='To-do']")` to work with checkboxes.

(I finally admitted defeat with my implementation being too buggy and ended up using this instead - I'm impressed with the difference in performance.)

**Comment by obahareth** [comment]
Really great work here @Fahme, this worked quite well with the scenarios I mentioned before. Thank you so much for helping to support this repository.

**Review by obahareth — APPROVED** [review]

**Comment by obahareth** [comment]
@all-contributors please add @Fahme for code contributions.

**Comment by obahareth** [comment]
This should be published to the Chrome store as soon as Google's team is done reviewing it.

**Pull request merged**
